apiVersion: v2
name: kube-workspaces
description: A Helm chart for deploying kube-workspaces (controller, API, and frontend)
type: application
version: 0.1.5
appVersion: "0.1.0"

dependencies:
  - name: dex
    version: "0.22.1"
    repository: "https://charts.dexidp.io"
    condition: dex.enabled
