apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - authconfig.yaml
  - auth-secrets.yaml
  - workspace-roles.yaml

patches:
  - path: api-env-patch.yaml
    target:
      kind: Deployment
      name: kube-workspaces-api
