#!/usr/bin/env bash
# generate-godoc.sh - Generates Markdown documentation for the Go packages in
# the controller, api and proxy repositories, then writes the combined output
# into the api repo for embedding in the API server.
#
# NOTE: this script predates the monorepo split. The components now live in
# separate repositories, so it needs the controller, api and proxy repos
# checked out alongside this one:
#
#   src/github/kube-workspaces/
#     ├── api/
#     ├── controller/
#     ├── proxy/
#     └── deploy/      <- you are here
#
# Override the locations with CONTROLLER_DIR / API_DIR / PROXY_DIR if your
# layout differs.
#
# Usage: ./scripts/generate-godoc.sh
# Output: $API_DIR/cmd/kube_workspaces/godoc/

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEPLOY_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
SIBLINGS="$(cd "$DEPLOY_DIR/.." && pwd)"

CONTROLLER_DIR="${CONTROLLER_DIR:-$SIBLINGS/controller}"
API_DIR="${API_DIR:-$SIBLINGS/api}"
PROXY_DIR="${PROXY_DIR:-$SIBLINGS/proxy}"

for d in "$CONTROLLER_DIR" "$API_DIR" "$PROXY_DIR"; do
  if [ ! -f "$d/go.mod" ]; then
    cat >&2 <<EOF
error: expected a Go module at $d

The components live in separate repositories since the monorepo
(github.com/flaccid/kube-workspaces, now archived) was split. Clone them
alongside this repo, or set CONTROLLER_DIR / API_DIR / PROXY_DIR explicitly:

  git clone https://github.com/kube-workspaces/controller "$SIBLINGS/controller"
  git clone https://github.com/kube-workspaces/api "$SIBLINGS/api"
  git clone https://github.com/kube-workspaces/proxy "$SIBLINGS/proxy"
EOF
    exit 1
  fi
done

OUTPUT_DIR="$API_DIR/cmd/kube_workspaces/godoc"

# Ensure gomarkdoc is available
if ! command -v gomarkdoc &> /dev/null; then
    echo "Installing gomarkdoc..."
    go install github.com/princjef/gomarkdoc/cmd/gomarkdoc@latest
fi

echo "Generating Go documentation..."
echo "  controller: $CONTROLLER_DIR"
echo "  api:        $API_DIR"
echo "  proxy:      $PROXY_DIR"
echo "  output:     $OUTPUT_DIR"

# Create output directory
rm -rf "$OUTPUT_DIR"
mkdir -p "$OUTPUT_DIR"

BRANCH="main"

# Derive each repo's URL from its module path so the links stay correct without
# hardcoding an org that may change again.
module_path() { awk '/^module /{print $2; exit}' "$1/go.mod"; }
CONTROLLER_MODULE="$(module_path "$CONTROLLER_DIR")"
API_MODULE="$(module_path "$API_DIR")"
PROXY_MODULE="$(module_path "$PROXY_DIR")"
CONTROLLER_URL="https://${CONTROLLER_MODULE}"
API_URL="https://${API_MODULE}"
PROXY_URL="https://${PROXY_MODULE}"

# Go version each module declares, for the index metadata.
go_version() { awk '/^go /{print $2; exit}' "$1/go.mod"; }

# Render one package's documentation into the given output file. Links point at
# the upstream repo when the checkout has a git remote; plain output is used
# otherwise (tarballs, CI caches). Strips the "generated by gomarkdoc" comment
# gomarkdoc emits at the top of every package section — it is just noise on the
# rendered docs page.
render_pkg() {
    local url="$1" out="$2" pkg="$3"
    local tmp
    tmp="$(mktemp)"
    if ! gomarkdoc --format github \
        --repository.url "$url" \
        --repository.default-branch "$BRANCH" \
        --repository.path "/" \
        "$pkg" > "$tmp" 2>/dev/null; then
        gomarkdoc --format github "$pkg" > "$tmp" 2>/dev/null || { rm -f "$tmp"; return 1; }
    fi
    grep -v '^<!-- Code generated by gomarkdoc. DO NOT EDIT -->$' "$tmp" >> "$out"
    echo "" >> "$out"
    rm -f "$tmp"
}

# --- Controller Module ---
echo "  -> Controller module ($CONTROLLER_DIR)"
cd "$CONTROLLER_DIR"

CONTROLLER_OUT="$OUTPUT_DIR/controller.md"
: > "$CONTROLLER_OUT"

CONTROLLER_PACKAGES=(
    "./api/v1alpha1"
    "./internal/controller"
)

for pkg in "${CONTROLLER_PACKAGES[@]}"; do
    echo "     - $pkg"
    render_pkg "$CONTROLLER_URL" "$CONTROLLER_OUT" "$pkg"
done

# --- API Module ---
echo "  -> API module ($API_DIR)"
cd "$API_DIR"

API_OUT="$OUTPUT_DIR/api.md"
: > "$API_OUT"

API_PACKAGES=(
    "."
    "./internal/auth"
    "./internal/k8s"
    "./internal/proxy"
    "./internal/exec"
)

for pkg in "${API_PACKAGES[@]}"; do
    echo "     - $pkg"
    render_pkg "$API_URL" "$API_OUT" "$pkg"
done

# --- Proxy Module ---
echo "  -> Proxy module ($PROXY_DIR)"
cd "$PROXY_DIR"

PROXY_OUT="$OUTPUT_DIR/proxy.md"
: > "$PROXY_OUT"

PROXY_PACKAGES=(
    "./cmd/proxy"
    "./internal/auth"
    "./internal/k8s"
    "./internal/proxy"
)

for pkg in "${PROXY_PACKAGES[@]}"; do
    echo "     - $pkg"
    render_pkg "$PROXY_URL" "$PROXY_OUT" "$pkg"
done

# --- Index metadata ---
cat > "$OUTPUT_DIR/index.json" << EOF
{
  "generated": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "modules": [
    {
      "name": "Controller",
      "path": "controller",
      "goVersion": "$(go_version "$CONTROLLER_DIR")",
      "module": "${CONTROLLER_MODULE}",
      "description": "Kubernetes controllers for Workspace, User, and AuthConfig CRDs",
      "packages": [
        "api/v1alpha1",
        "internal/controller"
      ]
    },
    {
      "name": "API",
      "path": "api",
      "goVersion": "$(go_version "$API_DIR")",
      "module": "${API_MODULE}",
      "description": "REST API service built with Goa",
      "packages": [
        ".",
        "internal/auth",
        "internal/k8s",
        "internal/proxy",
        "internal/exec"
      ]
    },
    {
      "name": "Proxy",
      "path": "proxy",
      "goVersion": "$(go_version "$PROXY_DIR")",
      "module": "${PROXY_MODULE}",
      "description": "Reverse proxy for workspace traffic (/proxy/{ns}/{name}/...)",
      "packages": [
        "cmd/proxy",
        "internal/auth",
        "internal/k8s",
        "internal/proxy"
      ]
    }
  ]
}
EOF

echo "Done. Generated:"
echo "  - controller.md ($(wc -l < "$CONTROLLER_OUT") lines)"
echo "  - api.md ($(wc -l < "$API_OUT") lines)"
echo "  - proxy.md ($(wc -l < "$PROXY_OUT") lines)"
echo "  - index.json"
